docs/data-sources/tenant.md
https://github.com/gpsinsight/terraform-provider-fusionauth/issues/32
=> Typo in doc header: Tentan-->Tenant

fusionauth/resource_fusionauth_application_crud.go, fusionauth/resource_fusionauth_application_role.go, fusionauth/resource_fusionauth_email.go, fusionauth/resource_fusionauth_form.go, fusionauth/resource_fusionauth_form_field.go, fusionauth/resource_fusionauth_group.go, fusionauth/resource_fusionauth_key.go, fusionauth/resource_fusionauth_lambda.go, fusionauth/resource_fusionauth_tenant_crud.go, fusionauth/resource_fusionauth_themes.go, fusionauth/resource_fusionauth_user.go, fusionauth/resource_fusionauth_user_registration.go, fusionauth/resource_fusionauth_webhook.go, fusionauth/resource_system_configuration.go
Idea lovingly borrowed from: https://github.com/gitlabhq/terraform-provider-gitlab/blob/a101a1c7f4405b22318f43a60628808a98a8b8ef/gitlab/resource_gitlab_group.go#L198
=> fix: nuke id if 404

README.md, docs/resources/user_action.md, fusionauth/provider.go, fusionauth/resource_fusionauth_user_action.go
=> Add user action resource

docs/data-sources/lambda.md, fusionauth/datasource_fusionauth_lambda.go, fusionauth/provider.go
=> Add fusionauth_lambda datasource

fusionauth/resource_fusionauth_entity_type.go
I missed a property in #85 I believe.
=> Set entity_type.jwt_configuration to computed

fusionauth/resource_fusionauth_entity_grant.go
This is a hybridization of the approach that I took in #82 for handling entities.
Adds ForceNew to the entity_id, recipient_entity_id, and user_id.
Also, the terraform Id is generated by concatenation.
=> Generate synthetic grant ids

docs/resources/entity_grant.md, fusionauth/resource_fusionauth_entity_grant.go
quickfix - realized I forgot to add in the entity grant documentation..
=> bugfix(docs): fixes entity grant documentation.

fusionauth/resource_fusionauth_entity_type_permission.go
Forces new records (and removal of old records) if a permission's name changes or the linked entity type id is changed.
=> bugfix(entity type permission): force new if entity id or permission name changes.

fusionauth/resource_fusionauth_user_registration.go
What's written on the tin really 👍
=> bugfix(user_registration): ensures specified timezones are configured in request payloads.

docs/resources/tenant.md, fusionauth/helpers.go, fusionauth/resource_fusionauth_tenant.go, fusionauth/resource_fusionauth_tenant_crud.go, fusionauth/resource_fusionauth_tenant_helpers.go, fusionauth/resource_fusionauth_tenant_test.go, fusionauth/resource_fusionauth_user_test.go
This PR adds the connector policy attribute to the tenant configuration (Issue #100)
=> feat: Add connector policy attribute to tenant.

fusionauth/resource_fusionauth_api_key.go
=> fix: force new api key if the key is changed

docs/resources/idp_saml_v2.md, fusionauth/resource_fusionauth_idp_samlv2.go
=> feat: add support for specifying nameIdFormat in idp_samlv2 resources

docs/resources/application.md, fusionauth/resource_fusionauth_application.go, fusionauth/resource_fusionauth_application_helpers.go
=> feature(application): adds support for `form_configuration.self_service_form_id`

README.md
This particular issue has caused a few folks some pain, so wanted to at least document it in the readme until cycles can be found to fix it.
=> Add 'known issues' section.

fusionauth/datasource_fusionauth_idp.go, fusionauth/helpers.go, fusionauth/idphelpers.go, fusionauth/resource_fusionauth_group.go, fusionauth/resource_fusionauth_tenant_test.go, fusionauth/resource_fusionauth_user_registration.go
Allow setting free form data to group objects. [API reference](https://fusionauth.io/docs/v1/tech/apis/groups#request-3)
Also, some linting fixes to pass CI.
=> Fix setting free form data on groups

docs/resources/idp_open_id_connect.md, fusionauth/resource_fusionauth_idp_open_id_connect.go
Adds some missed documentation for a couple of properties too :)
=> feat(idp_open_id_connect): adds support for `oauth2_unique_id_claim` and `oauth2_username_claim`.

docs/resources/webhook.md, fusionauth/resource_fusionauth_application_crud.go, fusionauth/resource_fusionauth_webhook.go, go.mod, go.sum
=> add tenant ids to webhook

fusionauth/resource_fusionauth_form.go
=> Don't set form_id since this causes a dirty plan where they are auto-generated

docs/resources/application.md, docs/resources/tenant.md, fusionauth/resource_fusionauth_application.go, fusionauth/resource_fusionauth_application_helpers.go, fusionauth/resource_fusionauth_tenant.go, fusionauth/resource_fusionauth_tenant_helpers.go
=> Feature: add support for verification strategy

fusionauth/resource_fusionauth_email.go
=> Add not-whitespace validation to email properties

docs/resources/application.md, fusionauth/resource_fusionauth_application.go, fusionauth/resource_fusionauth_application_helpers.go, fusionauth/resource_fusionauth_idp_samlv2.go, fusionauth/resource_fusionauth_idp_samlv2_idp_initiated.go, go.mod, go.sum
closes https://github.com/gpsinsight/terraform-provider-fusionauth/issues/180
=> feat: Add `authorized_url_validation_policy` to application resource

fusionauth/resource_fusionauth_application_helpers.go
=> feat: return client id from application

docs/resources/application.md, fusionauth/resource_fusionauth_application.go, fusionauth/resource_fusionauth_application_helpers.go
Title Says It All! 😄
API Docs: https://fusionauth.io/docs/v1/tech/apis/applications#create-an-application
=> feat(resource_fusionauth_application): add support for application level multifactor configuration.

docs/data-sources/lambda.md, docs/resources/application.md, docs/resources/lambda.md, fusionauth/datasource_fusionauth_lambda.go, fusionauth/resource_fusionauth_application.go, fusionauth/resource_fusionauth_application_helpers.go, fusionauth/resource_fusionauth_lambda.go
Added `SelfServiceRegistrationValidation` lambda type
=> Add `SelfServiceRegistrationValidation` lambda type

docs/guides/handling_default_resources.md, docs/index.md
* links to the FusionAuth hosted guide
* adds details about handling default resources
=> Adds some documentation to the terraform provider

README.md, docs/resources/theme.md, fusionauth/resource_fusionauth_themes.go, fusionauth/resource_fusionauth_themes_test.go, go.mod, go.sum
Resolves https://github.com/FusionAuth/terraform-provider-fusionauth/issues/271
=> Added the consent themed page for the 1.50 release
