FusionAuth/terraform-provider-fusionauth

docs/resources/tenant.md
fusionauth/schema_fusionauth_tenant.go

Noticed `randomDigits.` had a period on it and got a Terraform verification error when I copied over an example tenant block for `tenant.twoFactorOneTimeCodeIdGenerator`.

fix: fixes secure generator types.

---

docs/resources/api_key.md

fix(docs/resources/api_key.md): issue in documentation with terraform syntax missing a closing double quote

Fix: API Key Documentation

---

fusionauth/resource_fusionauth_application.go
fusionauth/resource_fusionauth_tenant.go

As per ending discussion in https://github.com/gpsinsight/terraform-provider-fusionauth/pull/82 this sets optional poperties to computed to suppress change detection.

Set properties that fusionauth auto-populates to Computed

---

fusionauth/resource_fusionauth_tenant.go

Enables support at the _tenant level_ for setting `encryption_scheme` to a custom-built encryptor.
Refer:
- https://fusionauth.io/docs/v1/tech/plugins/custom-password-hashing/

bugfix(tenant): enables support for 3rd-party password encryptor plugins at the tenant level

---

docs/resources/reactor.md
fusionauth/provider.go
fusionauth/resource_fusionauth_reactor.go

This PR adds the FusionAuth reactor as a terraform resource.
The reactor apis aren't standard CRUD apis, so this implementation is a little different: 
- The create and update methods both use the same POST api to update the license attributes
- The read method can't update the state when the reactor is licensed, since the GET api doesn't include the license attributes
- The create method doesn't return the id of the reactor (aka fusion auth instance) so I have made up an id. I think this will be ok, since there can be only one reactor.
I've left some comments in the code where things are a little different than for a normal resource.

Add fusion auth reactor resource

---

fusionauth/resource_fusionauth_tenant.go

The FusionAuth doco for the Tenant API uses "user.two-factor-method.remove" instead of the correct name "user.two-factor.method.remove", resulting in API errors if its use is attempted. The PR corrects the schema reference to the incorrect name.
See also: https://github.com/FusionAuth/fusionauth-site/pull/1206

fix: tenant webhook event name typo

---

docs/resources/key.md
fusionauth/resource_fusionauth_key.go
fusionauth/resource_fusionauth_key_test.go

This PR adds `kid` as an attribute of the key resource. 
The key resource only has a few arguments, but attributes such as the `kid` can be read and exported once the key has been created.

Add `kid` attribute to key resource.

---

docs/resources/group.md
fusionauth/resource_fusionauth_group.go

Manual testing:
```
resource "fusionauth_group" "example" {
name      = "example"
tenant_id = fusionauth_tenant.this.id
group_id  = "277d9794-99ca-45f9-8b55-163f8b228ddf"
}
```
```
No changes. Your infrastructure matches the configuration.  
```
```
resource "fusionauth_group" "example" {
name      = "example"
tenant_id = fusionauth_tenant.this.id
group_id  = "ad38306f-45e7-451b-a632-95a1bb6f21f1"
}
resource "fusionauth_group" "example2" {
name      = "example2"
tenant_id = fusionauth_tenant.this.id
}
```
```
Terraform will perform the following actions:
-/+ resource "fusionauth_group" "example" {
- data      = {} -> null
~ group_id  = "277d9794-99ca-45f9-8b55-163f8b228ddf" -> "ad38306f-45e7-451b-a632-95a1bb6f21f1" # forces replacement
~ id        = "277d9794-99ca-45f9-8b55-163f8b228ddf" …
```

Optionally pass group UUID

---

docs/data-sources/user.md
fusionauth/datasource_fusionauth_user.go
fusionauth/provider.go

Add data source for fetching a single user, either by username or ID.
Exposes mostly the same attributes as the user resource. `active` is added, and MFA related ones dropped.

feat: Add user data source

---

docs/data-sources/form.md
fusionauth/datasource_fusionauth_form.go
fusionauth/provider.go
fusionauth/resource_fusionauth_form.go

Silly little thing I've come across where applications need to have a self-service form set in order for users to configure their own MFA, but the default Form IDs are unique (i.e. not the same) across deployments...

feature(form): adds support for `fusionauth_form` as a data source.

---

fusionauth/resource_fusionauth_user_schema.go

Stops the following from happening after a user has configured MFA via the self-management portal:
🎉

bugfix(user): enables users to self-manage two-factor methods.

---

fusionauth/resource_fusionauth_user.go
fusionauth/resource_fusionauth_user_schema.go

Turns out `user.twoFactor.methods[x].id` is required to update a user with an `authenticator` two factor method configured.
The ID is used internally to track the lifecycle of the provided authentication method so FusionAuth doesn't have to return `HTTP 400` when a secret isn't provided.

feat(user): adds support for two factor method id.

---

docs/resources/user_action.md
fusionauth/helpers.go
fusionauth/resource_fusionauth_tenant_test.go
fusionauth/resource_fusionauth_user_action.go

We want to create the user action with an id that we provide. The terraform provider does not currently allow this: [Terraform Registry](https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/user_action) 
###Tasks
- adding test for the whole file resource_fusion_user_action

[feature] add user action id attribute to user action resource

---

fusionauth/resource_fusionauth_user_action.go

We recently implemented the ability to provide the `user_action_id` when creating a user action. However, we forgot to pass the id to the FusionAuth client.

fix(user_action): Pass the user action id to the FAClient

---

docs/resources/tenant.md
docs/resources/webhook.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_webhook.go

Referencing issue #148 - felt like a reasonably straightforward addition to support these new webhook event configurations [added in 1.36.0](https://fusionauth.io/blog/2022/04/15/announcing-fusionauth-1-36)

Add user.identity-provider.link/unlink added in 1.36.0

---

docs/resources/application.md
docs/resources/webhook.md
fusionauth/resource_fusionauth_application.go
fusionauth/resource_fusionauth_application_crud.go
fusionauth/resource_fusionauth_webhook.go
go.mod
go.sum

Partially resolves #144 
This updates the go client which is needed due to Content-Type header changes. I have also removed account/webhook relationships as these have been removed from FusionAuth - they need to be added back to the tenant.

Updates to support fusionauth 1.40.x

---

docs/resources/theme.md
fusionauth/resource_fusionauth_themes.go
fusionauth/resource_fusionauth_themes_test.go
go.mod
go.sum

This is my first time making changes to a Terraform plugin, writing Go, etc, so please let me know if there is something I missed. I _think_ I found all of the places where the theme files are referenced and updated them according to include the new templates. I tried to follow the existing naming conventions, formatting, etc, but I can change something if needed.
I am not familiar enough with Terraform to know the best approach for building and testing this against our dev instance of FusionAuth, so guidance is welcome on that front as well.

feat(themes): add support for WebAuthN-related theme files (fixes #159)

---

docs/resources/email.md
fusionauth/resource_fusionauth_email.go

Fix for #167
Per the API [documentation](https://fusionauth.io/docs/v1/tech/apis/emails#create-an-email-template), both `emailTemplate.defaultFromName` and `emailTemplate.fromEmail` are optional.

fusionauth_email: Make default_from_name and from_email optional

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go

Fixes #165
Note:
-  I didn't update the `github.com/FusionAuth/go-client` dependency since this would have involved more changes I considered beyond the scope of this MR. To this end, the `fusionauth.MultiFactorLoginPolicy_Required` isn't yet available and therefore you cannot set it to `Required` yet. Fixing that should be easy, though, after the dependency has been updated.

Fix tenant.multiFactorConfiguration.loginPolicy handling

---

fusionauth/resource_fusionauth_themes.go

Executing `terraform plan` results in a change detection for `oauth2_two_factor_enable` even if no changes are made to the resource (see https://github.com/gpsinsight/terraform-provider-fusionauth/issues/184). This is because it is accidentally pulling the value from the `oauth2_two_factor_enable_complete` template to compare against.

Correct the themes oauth2_two_factor_enable diff

---

fusionauth/resource_fusionauth_tenant.go

Related Issue: #184 
Related PR: #185
`login_policy` is an optional field, but when not set the fusionauth client (or API) appears to return "Enabled" as the default value. Without defining a similar default in the provider we get a change notification when running `terraform plan`:
```
~ resource "fusionauth_tenant" "REDACTED_tenant" {
id                                 = "REDACTED"
~ multi_factor_configuration         = [
~ {
~ login_policy  = "Enabled" -> null
},
]
name                               = "REDACTED"
}
```
This pull request sets the default value to "Enabled" which results in `terraform plan` correctly indicating that no changes will be applied.

add a default value for login_policy

---

docs/resources/lambda.md
fusionauth/resource_fusionauth_lambda.go

Like was done in #143/#150 for user actions this change allows you to specify the ID of a lambda when you create it.

Allow specifying the ID in a lambda

---

docs/data-sources/form.md
fusionauth/datasource_fusionauth_form.go
fusionauth/resource_fusionauth_form.go

Available since (presumably) 1.26. The API accepts the `selfServiceUser` input type. For comparison see typing of the fusionauth typescript client here: https://github.com/FusionAuth/fusionauth-typescript-client/blob/master/src/FusionAuthClient.ts#L7180-L7185

Add `selfServiceUser` form type

---

fusionauth/resource_fusionauth_application_helpers.go

This line was accidentally dropped during rebasing of https://github.com/gpsinsight/terraform-provider-fusionauth/pull/187

Send `authorized_url_validation_policy` when creating application

---

fusionauth/resource_fusionauth_application.go

This was a bug introduced in https://github.com/gpsinsight/terraform-provider-fusionauth/pull/196. The schema wasn't updated so any time the application resource was invoked, an invalid schema error was thrown.

Fixes #200 - Add client_id to newOAuthConfiguration app schema

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_test.go

Since FusionAuth 1.30.0 `access_token_key_id` & `id_token_key_id` are optional fields of `fusionauth_tenant.jwt_configuration[0]`.
[Source](https://fusionauth.io/docs/v1/tech/apis/tenants):
> tenant.jwtConfiguration.idTokenKeyId [UUID] OPTIONAL Defaults to key value of the FusionAuth application AVAILABLE SINCE 1.8.0
> The unique id of the signing key used to sign the Id token.
> 
> Prior to version 1.30.0 this value was required.
Fixes: [#203](https://github.com/gpsinsight/terraform-provider-fusionauth/issues/203)

fix: Tenant JWT Configurations

---

docs/data-sources/email.md
fusionauth/datasource_fusionauth_email.go
fusionauth/provider.go

Adds the Email Template Data Source from an Email Template's name. Exposes exactly the same attributes as the [Email Resource](https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/email).
Usage:
```hcl
data "fusionauth_email" "default_setup_password" {
name = "[FusionAuth Default] Setup Password"
}
resource "fusionauth_tenant" "example" {
name = "example"
email_configuration {
set_password_email_template_id = data.fusionauth_email.default_setup_password.id
...
```
plan output:
```
~ resource "fusionauth_tenant" "example" {
id                                 = "6081a8b0-b240-4c6b-bf97-f3ca1b545265"
name                               = "example"
~ email_configuration {
+ set_password_email_template_id = "2c8d6265-24ca-4d47-a60c-d8bb7abc7578"
```

feat: add Email Data Source

---

docs/data-sources/form_field.md
fusionauth/datasource_fusionauth_form_field.go
fusionauth/provider.go

Adds the Form Field Data Source. It exposes the same attributes as the [Form Field Resource](https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/form_field).
It can be used to retrieve the secure random UUID generated by the deployment and assigned to default Form Fields.

feat: add Form Field datasource

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go

Builds upon the changes introduced through #212. 🎉 
Also fixes an issue where the server response for rate limits weren't deserialised into terraform state.
This could lead to issues if a rouge operator happened to change a setting server-side and terraform wouldn't reconcile the differences.

feat(resource_fusionauth_tenant): adds support for all tenant rate limit configuration items.

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go
fusionauth/resource_fusionauth_themes_test.go
fusionauth/resource_fusionauth_user.go
fusionauth/resource_fusionauth_user_test.go
fusionauth/testdata/messages.properties.go

This PR depends on #215, otherwise test file conflicts would ensue.. 
Have a perusal there first, then I can rebase this PR as needed. 😄 
- chore(testdata): updates messages to fusionauth 1.46.0.
- chore(resource_fusionauth_themes_test): adds theme data for `Oauth2TwoFactorEnable` and `Oauth2TwoFactorEnableComplete`.
- chore(resource_fusionauth_user_test): multi-factor email/phone numbers can't be updated once created.
- chore(resource_fusionauth_user_test): ignores `disable_domain_block` and `parent_email` when performing a user import as the attributes aren't returned from the server.
- fix(resource_fusionauth_user): removes setting `parent_email` in terraform state as the server never returns the data.
- fix(resource_fusionauth_tenant): sets `jwt_configuration.access_token_key_id` and …

fix: marks tenant token ids as computed and disables setting user `parent_email` from server response in state.

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go
fusionauth/resource_fusionauth_themes_test.go
fusionauth/testdata/messages.properties.go

Update Fusionauth provider to support tenant captcha configuration.
Note: In order to make `tenant` unit tests working, we had to update some other non-related properties (was taken from https://github.com/gpsinsight/terraform-provider-fusionauth/pull/216).
[Tenant APIs](https://fusionauth.io/docs/v1/tech/apis/tenants#create-a-tenant)
https://github.com/gpsinsight/terraform-provider-fusionauth/pull/212

fix: update to support tenant captcha configuration

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go

Update Fusionauth provider to support `actionCancelPolicy` of the Tenant failed authentication configuration.
It's available since 1.42.0.
From API doc:
> tenant.failedAuthenticationConfiguration.actionCancelPolicy.onPasswordReset [Boolean] OPTIONAL Defaults to false AVAILABLE SINCE 1.42.0
Indicates whether you want the user to be able to self-service unlock their account prior to the action duration by completing a password reset workflow.

feat(resource_fusionauth_tenant): add failed authentication action cancel policy property

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go

`tenant.failedAuthenticationConfiguration.emailUser` was [added to the FusionAuth Tenant AP in version 1.42.0](https://github.com/FusionAuth/fusionauth-issues/issues/1823). This PR adds support for setting this value.
From the API Doc:
> tenant.failedAuthenticationConfiguration.emailUser [String] Optional defaults to false Available since 1.42.0
> 
> Indicates you would like to email the user when the user’s account is locked due to this action being taken. This requires the User Action specified by the tenant.failedAuthenticationConfiguration.userActionId to also be configured for email. If the User Action is not configured to be able to email the user, this configuration will be ignored. See userEmailingEnabled on the User Action.
> 
> The email template configuration will be in the …

Add email user setting to failed auth configuration of tenant resource

---

fusionauth/resource_system_configuration.go

When using Terraform to make changes to the login records section of the system configuration settings, a terraform apply indicates that changes are always required. This is because the when reading the state of the login records settings from Fusion Auth there is a bug in the code that is causing the login records settings to be read from the admin logs settings fields. I believe these changes should correct this.

fix: login records information being incorrectly read from admin logs fields

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go

This add support for creating tenant with 'Required' multifactor login policy 
**From ducumentation:**
https://fusionauth.io/docs/v1/tech/apis/tenants
tenant.multiFactorConfiguration.loginPolicy
Supported values include:
**Enabled** - Require a two-factor challenge during login when an eligible method is available.
**Disabled** - Do not require a two-factor challenge during login.
**Required** - Require a two-factor challenge during login. A user will be required to configure 2FA if no eligible methods are available. AVAILABLE SINCE 1.42.0

Add 'Required' option to tenant multi_factor_configuration.login_policy

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go

Adds support for `tenant.emailConfiguration.additionalHeaders` (see https://fusionauth.io/docs/v1/tech/apis/tenants), which so far used to be commented-out.
Plan output from local testing:
```
Terraform will perform the following actions:
~ resource "fusionauth_tenant" "users" {
id                                 = "<ID>"
name                           = "users"
~ email_configuration {
~ additional_headers                  = {
+ "X-Mailgun-Drop-Message" = "yes"
}
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```

feat: add support for email configuration additional headers

---

docs/resources/theme.md

Adding a little more information to Theme docs and also correcting the link to FusionAuth's docs

Theme doc typo correction

---

docs/resources/application.md
fusionauth/resource_fusionauth_application.go
fusionauth/resource_fusionauth_application_helpers.go
fusionauth/resource_fusionauth_email.go
fusionauth/resource_fusionauth_generic_connector.go
fusionauth/resource_fusionauth_generic_connector_test.go
go.mod
go.sum

* feat: Updated the FusionAuth go client to the latest version for 1.47.1
* feat(resource_fusionauth_application): Support the new preferred_languages field in application registration configuration
* fix(resource_fusionauth_email): Prevent localized email templates from perpetually registering as changed

Update go client, update app registration config, fix localized email templates

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go

Version 1.46.0 of FusionAuth introduced the following new configuration options for `tenant.jwtConfiguration`:
1. `refreshTokenExpirationPolicy`: `SlidingWindowWithMaximumLifetime`
2. `refreshTokenSlidingWindowConfiguration.maximumTimeToLiveInMinutes`
See: https://fusionauth.io/docs/v1/tech/apis/tenants
These changes aim to allow managing these values via the terraform provider. Specifically:
- Added `SlidingWindowWithMaximumLifetime` as an allowed value for `jwt_configuration`.`refresh_token_expiration_policy`
- Added `refresh_token_sliding_window_maximum_time_to_live_in_minutes` to `jwt_configuration` for setting a custom TTL value
- Updated documentation

Add refresh token sliding window configuration

---

docs/resources/theme.md
fusionauth/resource_fusionauth_themes.go
go.mod
go.sum

This PR adds support for Confirmation Required Template that was introduced in 1.49.0 update.
https://fusionauth.io/docs/apis/themes#create-a-theme
This PR unblocks theme updates for versions > 1.49.0

FusionAuth 1.49.0 Add 'Confirmation Required' template to resource_fusionauth_themes to fix theme

---

fusionauth/resource_fusionauth_themes.go

This fixes a bug for the template originally introduced in this PR https://github.com/FusionAuth/terraform-provider-fusionauth/pull/263
`confirmation_required` was wrongly referencing the `account_two_factor_index` template and was showing diffs between the wrong templates on plan

Fix wrong reference to Confirmation Required template

---

fusionauth/resource_fusionauth_idp_apple.go

Bundle ID is needed for working native app logins. Based on the [api](https://fusionauth.io/docs/apis/identity-providers/apple) this should be able to be supplied via `identityProvider.bundleId`

Add missing bundle_id to idp_apple resource

---

fusionauth/helpers.go
fusionauth/resource_fusionauth_application.go
fusionauth/resource_fusionauth_application_helpers.go
fusionauth/resource_fusionauth_form_field.go

* fixed issue with options order not being preserved for `form_field` object

199 - Order of options in form field

---

docs/resources/application.md
fusionauth/resource_fusionauth_application.go
fusionauth/resource_fusionauth_application_helpers.go

Add OAuth configuration support for:
* scope_handling_policy
* unknown_scope_policy
* relationship
* consent_mode
Add userinfo_populate_lambda_id.
Update provided_scope_policy to not want to re-apply on every run.
Fixes #283

Add support for OAuth scope handling

---

docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_crud.go

Fix https://github.com/FusionAuth/terraform-provider-fusionauth/issues/257
Tenant API requests for [POST](https://fusionauth.io/docs/apis/tenants#request) and [PUT](https://fusionauth.io/docs/apis/tenants#request-3), support `webhookIds` to link webhooks to tenants
Tenant [GET](https://fusionauth.io/docs/apis/tenants#response-1), [POST](https://fusionauth.io/docs/apis/tenants#response) and [PUT](https://fusionauth.io/docs/apis/tenants#response-3) responses do not return `webhookIds`, so we're unable to see a diff based on remote state.

Support tenant webhookids

---

docs/guides/handling_default_resources.md
docs/resources/tenant.md
fusionauth/resource_fusionauth_tenant.go
fusionauth/resource_fusionauth_tenant_helpers.go
fusionauth/resource_fusionauth_tenant_test.go
go.mod
go.sum

- https://github.com/FusionAuth/fusionauth-issues/issues/2736
- https://linear.app/fusionauth/issue/ENG-988/[bug]-cannot-log-in-anymore-after-upgrade-to-v150x
Add `login_intent_time_to_live_in_seconds` external identifier configuration for the tenant.
- https://github.com/FusionAuth/fusionauth-app/pull/452
- https://github.com/FusionAuth/fusionauth-client-builder/pull/89

Add login intent Id TTL to tenant configuration

---

docs/resources/system_configuration.md
fusionauth/resource_system_configuration.go

- https://github.com/FusionAuth/fusionauth-issues/issues/1314
- https://linear.app/fusionauth/issue/ENG-175/add-a-webhook-event-log
Add `webhook_event_log_configuration` to system configuration.
- https://github.com/FusionAuth/fusionauth-app/pull/436
- https://github.com/FusionAuth/fusionauth-client-builder/pull/83

Add webhook event log retention policy configuration

---

fusionauth/resource_fusionauth_idp_google.go

Replaces `LinkByEmail` with `UseVendorJavaScript`.
Fixes #284

Fix the login method validation for Google IDP
